### ISSUE TITLE
Primary key in cache objects set to invalid value

### ISSUE THREAD

**Issue by emilof** [Roobiq/RBQFetchedResultsController#1]
Hi.

I think primaryKeyStringValue of RBQObjectCacheObject is set to an invalid value when the primary key is of type NSInteger. FRC returns correct number of sections and rows but method [RBQFRC objectInRealm:atIndexPath:] always returns nil.

When replacing following code (line 30) in file 'RBQObjectCacheObject.m':
        cacheObject.primaryKeyStringValue = @((NSInteger)primaryKeyValue).stringValue;
with:
        cacheObject.primaryKeyStringValue = ((NSNumber *)primaryKeyValue).stringValue;
It works as it should

Seems like "[RLMObject primaryKeyValueForObject:];" returns an NSNumber* not an NSInteger.

**Comment by bigfish24** [comment]
Yes this is a bug. Looking in the Realm code base, all RLMObject subclasses override objectForKeyedSubscript: to call RLMDynamicGet function, which returns an NSNumber for the numerical properties. I will push an update to fix. Thanks!

**Comment by bigfish24** [comment]
Ok the changes should now be live. Updated the version to v1.4.8, and updated pod. Neither the example project or our other projects using the code had primary keys that were not strings, so this slipped by. Thanks again!
