### ISSUE TITLE
ClassName with Swift Frameworks

### ISSUE THREAD

**Issue by ncperry** [Roobiq/RBQFetchedResultsController#11]
I'm pulling Realm and RBQFetchedResultsController into our swift app that uses a bunch of in-house frameworks. In particular we have a RLMObject that we call RealmCourse that lives in the Swift framework CourseKit. Thus for namespacing, the correct class name is "CourseKit.RealmCourse". However when this gets put through:`+ (NSString *)classNameForObject:(RLMObject *)object` the className gets set to "Courses.RealmCourse", where "Courses" is the name of our app, as opposed to the framework the RealmCourse actually lives in. This causes our fetched results controller to always return nil because of the improper naming. I was able to fix it on our side by simply adding a category on RBQObjectCacheObject:

```
#import "RBQObjectCacheObject+SwiftFrameworkNaming.h"

@implementation RBQObjectCacheObject (SwiftFrameworkNaming)

+ (instancetype)createCacheObjectWithObject:(RLMObject *)object
                        sectionKeyPathValue:(NSString *)sectionValue
                                  className:(NSString *)className
{
    
    RBQObjectCacheObject *cacheObject = [RBQObjectCacheObject createCacheObjectWithObject:object sectionKeyPathValue:sectionValue];
    cacheObject.className = className;
    
    return cacheObject;
}

@end
```
And in RBQFetchedResultsController I changed createCacheWithRealm:cacheName:forFetchRequest:sectionNameKeyPath: to call my new category method: 
```
            RBQObjectCacheObject *cacheObject = [RBQObjectCacheObject createCacheObjectWithObject:object
                                                                              sectionKeyPathValue:currentSectionTitle
                                                                                        className:fetchRequest.entityName];
```

So just an fyi. It's working for me with my little fix.

**Comment by bigfish24** [comment]
Thanks for letting me know about this. I didn't think about how frameworks come into play with the class names. I am not sure if there is a way to detect that the RLMObject lives in a framework and get the framework name versus the app name. I will look into this because that would be ideal. The alternative is to have a method where you can "register" the framework name when creating a FRC instance, and that would be used instead of the app name.

**Comment by ncperry** [comment]
Is there a reason not to read it in From the fetchRequest. Is my solution going to break something?

**Comment by bigfish24** [comment]
Actually it will break the creation of the RBQSafeRealmObjects too, which are what get passed around in the notifications. I actually have a fix that I will push to a branch for you to test.

**Comment by bigfish24** [comment]
Ok, try this branch of FRC: https://github.com/Roobiq/RBQFetchedResultsController/tree/swift-frameworks

This uses the latest code that I pushed to RealmUtilities submodule. I am pretty sure it should work fine, the issue is that I was just using the main bundle to get the "app name" since Swift classes are appName.className, but the "app name" is really just the name of the main bundle, which frameworks have their own so I should just use the bundle name that corresponds to the class. Luckily NSBundle has an easy class method to figure this out.

If it works for you then I will merge into master for FRC.

The change was pretty simple:

```objc
NSBundle *classBundle = [NSBundle bundleForClass:[object class]];
    
NSString *bundleName = [classBundle objectForInfoDictionaryKey:@"CFBundleName"];
    
NSString *swiftClassName = [NSString stringWithFormat:@"%@.%@",bundleName,className];
```

versus
```objc
NSString *appName = [[NSBundle mainBundle] objectForInfoDictionaryKey:@"CFBundleName"];
    
NSString *swiftClassName = [NSString stringWithFormat:@"%@.%@",appName,className];
```

**Comment by ncperry** [comment]
I tried that fix, and unfortunately it didn't work for me. It was still doing Courses.Course. I checked target membership and Course is in CourseKit, not in Courses.

**Comment by bigfish24** [comment]
Hmm, does:

```objc
NSBundle *classBundle = [NSBundle bundleForClass:[object class]];
```
return a different bundle than the main bundle when you pass in your RLMObject that lives in CourseKit?

**Comment by ncperry** [comment]
No unfortunately not.
```
(lldb) po classBundle
NSBundle </Users/nperry/Library/Developer/CoreSimulator/Devices/691FC960-E9DF-4DE5-8BB9-8BE5D4396613/data/Containers/Bundle/Application/091B376E-5BD6-4C47-9126-297CC10400FF/Assignments.app> (loaded)

(lldb) po [NSBundle mainBundle]
NSBundle </Users/nperry/Library/Developer/CoreSimulator/Devices/691FC960-E9DF-4DE5-8BB9-8BE5D4396613/data/Containers/Bundle/Application/091B376E-5BD6-4C47-9126-297CC10400FF/Assignments.app> (loaded)
```

**Comment by ncperry** [comment]
Randomly when I do bundleForClass for RLMObject it does work:
```
(lldb) po [NSBundle bundleForClass:[RLMObject class]]
NSBundle </Users/nperry/Library/Developer/CoreSimulator/Devices/691FC960-E9DF-4DE5-8BB9-8BE5D4396613/data/Containers/Bundle/Application/091B376E-5BD6-4C47-9126-297CC10400FF/Assignments.app/Frameworks/Realm.framework> 
```

**Comment by bigfish24** [comment]
Ok, let me look into this a bit further. Really would like to have the plugin do this transparently rather than having to register the className through an API.

**Comment by bigfish24** [comment]
Ok, I think I have a fix. Testing now...

**Comment by bigfish24** [comment]
Ok, pull the latest from the swift-frameworks branch. This has code to get the original class from the RLMObject subclass and not the dynamically generated class which is what gets returned if you just call:

```
[object class]
```

Let me know if that works.

**Comment by bigfish24** [comment]
The original class is in the object's objectSchema but is a private property. So had to hack around to get access to. Here's the relevant code:

```objc
+ (NSString *)classNameForObject:(RLMObject *)object
{
...
@try {
        Class objectClass = [object.objectSchema valueForKey:@"objectClass"];
        
        NSBundle *classBundle = [NSBundle bundleForClass:objectClass];
        
        NSString *bundleName = [classBundle objectForInfoDictionaryKey:@"CFBundleName"];
        
        NSString *swiftClassName = [NSString stringWithFormat:@"%@.%@",bundleName,className];
        
        return swiftClassName;
    }
    @catch (NSException *exception) {
        if (exception.name == NSUndefinedKeyException) {
            @throw [NSException exceptionWithName:@"RBQException"
                                           reason:@"RLMObjectSchema doesn't contain original objectClass. Please file a GitHub issue regarding this."
                                         userInfo:nil];
        }
        else {
            @throw;
        }
    }
    
    @throw [NSException exceptionWithName:@"RBQException"
                                   reason:@"Class name for the RLMObject could not be found."
                                 userInfo:nil];
```

**Comment by ncperry** [comment]
That fixed my problem thanks!

**Comment by bigfish24** [comment]
Awesome, I will merge it into the FRC repo.

**Comment by bigfish24** [comment]
FRC now has changed merged in: https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v1.8.5
