### ISSUE TITLE
RealmSwift 2.1.1

### ISSUE THREAD

**Issue by phatblat** [Roobiq/RBQFetchedResultsController#111]
To finish up #103, a temporary [hack](https://github.com/Roobiq/RBQFetchedResultsController/pull/103#issuecomment-264389667) was employed to get around an issue that only occurs when this library is not built as a framework. RealmSwift 2.1.1 introduced some [converter functions](https://github.com/realm/realm-cocoa/blob/master/RealmSwift/ObjectiveCSupport.swift#L139-L147) which address this issue.

Replace the hack with the new API and set 2.1.1 to be the minimum RealmSwift version.

**Comment by bigfish24** [comment]
Fixed in https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v5.0.1
