### ISSUE TITLE
Helper function for sectionForSectionName

### ISSUE THREAD

**Issue by nanoxd** [Roobiq/RBQFetchedResultsController#12]
Hi,

Thanks for your hard work on this project. It's been a great alternative to `NSFetchedResultsController`. I was wondering if there was anything on the roadmap for adding a `sectionForSectionName` helper function?

**Comment by bigfish24** [comment]
This is definitely possible, what is the use case?

**Comment by nanoxd** [comment]
I have my table view sectioned like "Tuesday 5/27/15". For convenience I take a user to the current date by figuring out the section index by calling `sectionForSectionName`:

```swift
var todaySection: Int {
  get {
    let sectionName = NSDate().shortDateFromString()
    let index = viewModel.dataModel.sectionForSectionName(sectionName)
    return index
  }
}
```

I could then use this section to scroll to near that indexPath and style the header differently.

**Comment by bigfish24** [comment]
Ok, I guess there really isn't a cleaner way to do it. I was thinking of maybe adding a property `sections` that would return an `NSArray` of `RBQFetchedResultsSectionInfo` objects, but this would revert my initial hesitation of having that property in the first place. The `RBQFetchedResultsSectionInfo` objects retain a `RLMResults` so this makes them not thread-safe. Instead, just adding a method to do what you need would be easier.

**Comment by bigfish24** [comment]
Ok added the method:

```
sectionIndexForSectionName:
```

try it out in the indexForSectionName branch:
https://github.com/Roobiq/RBQFetchedResultsController/tree/indexForSectionName

**Comment by nanoxd** [comment]
I'm attempting to test it out but I'm getting a "RBQSafeRealmObject.h not found"

**Comment by bigfish24** [comment]
You have to initialize the submodules. The full list of commands is this:

```
git clone http://github.com/Roobiq/RBQFetchedResultsController
cd RBQFetchedResultsController/RBQFetchedResultsController
git submodule init
git submodule update
```
alternatively you can simplify it by just calling:
```
git clone --recursive http://github.com/Roobiq/RBQFetchedResultsController
```

**Comment by nanoxd** [comment]
Thanks, I was using Cocoapods to grab it and assumed that it would grab them for me.

**Comment by nanoxd** [comment]
I'm getting an error on `performMigrationForRealmAtPath`
```
/RBQFetchedResultsController/RBQFetchedResultsController/RBQFetchedResultsController.m:1984:32: 

Incompatible block pointer types sending 'void (^)(RLMMigration *__strong, NSUInteger)' to parameter of type 'RLMMigrationBlock' (aka 'void (^)(RLMMigration *__strong, uint64_t)')
```

Changing it to `uint64_t` made it work long enough to test it out. Works well :+1: 

Thanks
![](http://media2.giphy.com/media/tGokBeqpHuSgE/giphy.gif)

**Comment by bigfish24** [comment]
Awesome, I will merge that branch into the main branch and update CocoaPods so you can just update from there. That block of code that is causing that problem doesn't even need to be there, I will clean that up with the update too. Glad all is working!
