### ISSUE TITLE
`- (id)objectInRealm:atIndexPath:` is needed?

### ISSUE THREAD

**Issue by yuuki1224** [Roobiq/RBQFetchedResultsController#18]
This method is needed?
https://github.com/Roobiq/RBQFetchedResultsController/blob/master/RBQFetchedResultsController/RBQFetchedResultsController.h#L265

My thought is that `RBQFetchedResultsController` and `RBQFetchedRequest` is always 1 to 1. So `RBQFetchedRequest` can specify Realm path. I think [`RBQFetchedResultsController` has always specify one Realm path](https://github.com/Roobiq/RBQFetchedResultsController/blob/master/RBQFetchedResultsController/RBQFetchRequest.h#L32).

And just curious if it will be passed another Realm that is different with the Realm path that `RBQFetchedRequest` has, what will it be?

If this is needed with some reason, sorry and close this issue.

**Comment by bigfish24** [comment]
That method was put in place along side:

```objc
initWithFetchRequest:sectionNameKeyPath:inMemoryRealmCache:
```
so that you could create the in-memory Realm external to the FRC. I really should rethink this, because if anything you should only be passing in the identifier to the in-memory Realm, since presumably you already have a strong reference to it elsewhere.

**Comment by bigfish24** [comment]
If I remember correctly in-memory Realms initially were not accessible across threads, which in some way led to this early thinking in the API.

**Comment by bigfish24** [comment]
Fixed in this PR: https://github.com/Roobiq/RBQFetchedResultsController/pull/23
