### ISSUE TITLE
Project Architecture

### ISSUE THREAD

**Issue by yuuki1224** [Roobiq/RBQFetchedResultsController#25]
I think, for now it's difficult to contribute `RBQFetchedResultsController` itself because it doesn't show in Xcode navigation when I open `RBQFetchedResultsControllerExample.xcworkspace` (just show `Pods/RBQFetchedResultsController`)

So maybe option to solve this problem are
`RBQFetchedResultsController` from Podfile in example project and Example project includes the source code of `RBQFetchedResultsController`.
or 
Create `RBQFetchedResultsController` library target.

What do you think? @bigfish24

**Comment by nanoxd** [comment]
On that note, making this a Framework would make it easier to see the project and it's dependencies. It also opens up the door for Carthage support :wink:

**Comment by bigfish24** [comment]
Well that might be the way to go. I did pod install so it was simpler than doing the extra calls to pull in the submodules.

**Comment by bigfish24** [comment]
I will work to get this setup as a framework and with Carthage.

**Comment by thbaja** [comment]
:+1:

**Comment by enricenrich** [comment]
@bigfish24 any news on this? 😊

**Comment by bigfish24** [comment]
Well this is a little embarrassing since I said I would get to it about 6 months ago... I ran into some issues when I first attempted, but I need to revisit. Will try to find time over the next week to create a proper Xcode project that creates a framework for Carthage to use.

**Comment by bigfish24** [comment]
This PR should add Carthage once we can integrate it: https://github.com/Roobiq/RBQFetchedResultsController/pull/57

**Comment by bigfish24** [comment]
Carthage support finally added in [version 3.0](https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v3.0)!
