### ISSUE TITLE
Why isn't the cache folder stored in Caches?

### ISSUE THREAD

**Issue by benguild** [Roobiq/RBQFetchedResultsController#30]
Just wondering. Seems like a more logical place for it so that iCloud isn't backing it up without a manually set exclusion....

**Comment by bigfish24** [comment]
In my initial testing with a device the scroll performance was slower, because when you ask for the object at an index, it has to look up in the cache Realm then go to the main Realm. For whatever reason when the cache Realm was in the caches directory, it would take longer.

**Comment by benguild** [comment]
Got it.
