### ISSUE TITLE
Support for notifications on updates made on a RLMResult

### ISSUE THREAD

**Issue by mcgregok** [Roobiq/RBQFetchedResultsController#31]
https://github.com/realm/realm-cocoa/issues/1172

You can do bulk updates to objects in an RLMResult by calling `setValue:ForKey:` on it.  Any plans on adding categories for notifications to RLMResults to be able to support this?

**Comment by bigfish24** [comment]
yeah that is a good idea, I will add it

**Comment by bigfish24** [comment]
Ok added it with this commit: https://github.com/Roobiq/RBQFetchedResultsController/commit/59f7eda595527279bf46ca6c27dfe5b154086d9c

just update your pod to get it.

**Comment by mcgregok** [comment]
Awesome!  Thanks for maintaining this project and helping tackle one of the largest deficiencies in Realm.

**Comment by bigfish24** [comment]
No problem! I needed it and wanted to contribute back.
