### ISSUE TITLE
applyDerivedChangesToCache index out of bounds

### ISSUE THREAD

**Issue by ncperry** [Roobiq/RBQFetchedResultsController#36]
We have seen this issue in a smaller percentage of our user base. Any idea where to start on debugging it?
<img width="964" alt="screen shot 2015-08-31 at 9 36 05 am" src="https://cloud.githubusercontent.com/assets/1417659/9582682/1570b43e-4fc4-11e5-87e9-d3491c77f9d7.png">

**Comment by bigfish24** [comment]
How do you handle write transactions in the app? Are they all performed on a serial background queue?

**Comment by ncperry** [comment]
It's on the main thread.

**Comment by bigfish24** [comment]
Ok that rules out threading issues since main is serial. What version of FRC are you using and which version of Realm?

**Comment by ncperry** [comment]
Hmm we pulled RBQ into our project so we weren't tracking it using CocoaPods or Carthage. (We're using it inside a swift framework, so we didn't want to do CocoaPods inside a framework.) Is there an easy way to check the version?

I'm on 0.94.1 for Realm.

**Comment by bigfish24** [comment]
If it is a submodule you can type:
```
git submodule status
```
to get the commit ID

**Comment by ncperry** [comment]
We didn't submodule it. We literally just pulled in the code.

**Comment by bigfish24** [comment]
Hmm do you know roughly when you pulled the code?

**Comment by ncperry** [comment]
Looks like 5/28/15

**Comment by ncperry** [comment]
So maybe we do need to track the source somehow. CocoaPods still won't work for us. I noticed in another thread that you are working on Carthage support. Is that working now?

**Comment by ncperry** [comment]
Did some more digging. And I have no idea if this is relevant. I am writing on the main thread, but it looks like there are multiple background listeners. This is from Crashlytics:
<img width="325" alt="screen shot 2015-09-01 at 9 35 38 am" src="https://cloud.githubusercontent.com/assets/1417659/9608761/27421e90-508d-11e5-93e8-4a2da4498f1e.png">

**Comment by bigfish24** [comment]
No that is normal. Every Realm instance creates a notification listener on background thread to handle automatically refreshing data changes from one realm instance to the next. I was traveling yesterday, will look into it a bit more. Would say though that given how old your pull of the code is, you should update to the latest. However, the latest (2.0) requires Realm 0.95.

**Comment by ncperry** [comment]
K I'll try to update. Thanks.

**Comment by bigfish24** [comment]
Can you check if the error is occurring due to a section insert or a row insert? (i.e. in `applyDerivedChangesToCache:state:` is the error in the loop over derived section changes or derived object changes)

**Comment by ncperry** [comment]
Looking at the stack trace we are updating an object. We section by date. So if an object gets it's date updated, that could certainly result in a section being created and another section being created or updated. 

Another interesting anomaly is we have seen this crash 5741 and we have had 5741 users see the crash. So each user that does have it happen, sees it happen exactly once. And then is good.

**Comment by bigfish24** [comment]
Can you tell me what is the code at line 915 for you?

**Comment by bigfish24** [comment]
Did the code update fix the issue?

**Comment by ncperry** [comment]
Hey sorry, things got a little crazy here. If the database got deleted while the FRC was tracking could that cause this issue?

**Comment by bigfish24** [comment]
Sorry for my delay in responding. I was traveling in Europe. If the database got deleted while the FRC was tracking that would probably be the cause. The FRC creates a cache representation of the table state (including the sections) in a second Realm (either in-memory or persisted), and then when changes occur in the main Realm, this cache is used to find the differences. If you delete the main Realm file and create a new one, the cache might not have been rebuilt, so it would throw an index out of bounds error potentially when trying to figure out the changes applied to the new main Realm.

Does this make sense?

To fix, you should call `reset` on the FRC after the main Realm is deleted/recreated. This will delete the cache and rebuild it, so that it matches the new Realm.

**Comment by bigfish24** [comment]
I believe I have fixed the bug in the latest release.
