### ISSUE TITLE
Comparator for section titles

### ISSUE THREAD

**Issue by TiagoVeloso** [Roobiq/RBQFetchedResultsController#37]
I would like to use a custom comparator for section titles.

I know it has a drawback in performance with Realm.

But Alphabetical order is not "good" enough for my case.

I need to push "#" to the end, after the normal letters.

Is that possible?

**Comment by bigfish24** [comment]
Just to clarify, you need to sort the sections in a different order than Realm provides with their sorting by key?

**Comment by TiagoVeloso** [comment]
Yes.

But I did this another way. I've added a "sortOrder" column to my model.

**Comment by bigfish24** [comment]
Yeah that is the better way in terms of performance. Realm does plan to support more sorting functionality in the future.
