### ISSUE TITLE
Swift 2.0

### ISSUE THREAD

**Issue by bcapps** [Roobiq/RBQFetchedResultsController#38]
Realm currently has a RelamSwift Swift 2.0 branch that allows building using Xcode 7 and Swift 2.0. Have you thought about a similar setup? Unfortunately using that Realm branch and the current `SwiftFetchedResultsController` does not work, as there are build errors.

**Comment by bigfish24** [comment]
Yeah, I would like to get this working.... hopefully by the end of the week.

**Comment by student413** [comment]
Trying to use this in my project, but I need Swift 2 support — keep us updated!

**Comment by bigfish24** [comment]
Sorry for the delay. Swift 2.0 support was added in v2.2: https://github.com/Roobiq/RBQFetchedResultsController/commit/44539d19c29b90e678a1d35d07b01da5a76dbe9c
