### ISSUE TITLE
RBQRealmChangeLogger didAddObjects doesn't trigger FRC update

### ISSUE THREAD

**Issue by crsantos** [Roobiq/RBQFetchedResultsController#40]
I don't know if this is a bug or some mis-configuration of my project, but the thing is: updates/deletes are always propagated to the FRC, but creates don't.

Sample:
            ```[[RBQRealmChangeLogger defaultLogger] didAddObjects:createdObjects];```

I have breakpoints on the following callbacks but not a single one is fired for a *create* action (only for update/delete):
```
- (void)controllerWillChangeContent:(RBQFetchedResultsController *)controller;
- (void)controller:(RBQFetchedResultsController *)controller
   didChangeObject:(RBQSafeRealmObject *)anObject
       atIndexPath:(NSIndexPath *)indexPath
     forChangeType:(NSFetchedResultsChangeType)type
      newIndexPath:(NSIndexPath *)newIndexPath;
- (void)controller:(RBQFetchedResultsController *)controller
  didChangeSection:(RBQFetchedResultsSectionInfo *)sectionInfo
           atIndex:(NSUInteger)sectionIndex
     forChangeType:(NSFetchedResultsChangeType)type;
- (void)controllerDidChangeContent:(RBQFetchedResultsController *)controller;
```

I'm using release **2.2** and Realm **0.95.3**

**Comment by bigfish24** [comment]
Can you provide more of the source code? Very doubtful this is the library since this functionality is fully tested.

**Comment by crsantos** [comment]
Well, I just persisted some objects and call ```[[RBQRealmChangeLogger defaultLogger] didAddObjects:createdObjects];``` after. I was thinking if this is something related with the internal cache. Reseting cache is something that I didn't test but will do asap

**Comment by bigfish24** [comment]
@crsantos do the objects have primary keys?

**Comment by crsantos** [comment]
The main object, yes, it has PK, but it also has a ```RLMArray``` property of objets that don't have a PK. Could be because of that?

**Comment by crsantos** [comment]
One weeeeeeird thing that I noticed is... if I add/change objects and call the ``didChangeObjects:/didAddObjects:`` AFTER ``[realm commitWriteTransaction];``, sometimes it doesn't reload the correct values, *however*, if I call it BEFORE the ``[realm commitWriteTransaction];`` , everything works...

Any clue?

**Comment by crsantos** [comment]
I'm going to close this one as I can't replicate this anymore since I called ``didChange/didAdd`` inside transactions.

**Comment by bigfish24** [comment]
@crsantos sorry for my slow reply, was literally just typing! You definitely need to call the notification methods before `commitWriteTransaction` because all changes registered in the transaction get lumped together in 1 notification that is sent synchronously on the `commitWriteTransaction` call

**Comment by crsantos** [comment]
No problem, I've figured that out eventually.
I was seeing some notifications about this repo and reminded myself to close this old one.

Thanks for you hard work on this FRC :+1:

**Comment by bigfish24** [comment]
Thanks! Glad my slowness didn't slow you down...
