### ISSUE TITLE
Inserting new sections fails on iOS9 (iOS8 works fine)

### ISSUE THREAD

**Issue by mladjan** [Roobiq/RBQFetchedResultsController#42]
2015-10-17 22:48:15.744 Stellup[94318:24976924] Inserting section at 0
2015-10-17 22:48:15.745 Stellup[94318:24976924] Inserting section at 1
2015-10-17 22:48:15.745 Stellup[94318:24976924] Inserting section at 2
2015-10-17 22:48:15.747 Stellup[94318:24983296] 3 Derived Inserted Sections
2015-10-17 22:48:15.748 Stellup[94318:24983296] 0 Derived Deleted Sections

RBQFecthResultsTVC caught exception updating table view: Invalid update: invalid number of sections.  The number of sections contained in the table view after the update (3) must be equal to the number of sections contained in the table view before the update (0), plus or minus the number of sections inserted or deleted (0 inserted, 0 deleted).. Falling back to reload.

**Comment by bigfish24** [comment]
Can you provide more details?

**Comment by antigp** [comment]
I think you don't correct implement -didChangeSection:atIndex:forChangeType:

Try this
    func controller(controller: RBQFetchedResultsController, didChangeSection section: RBQFetchedResultsSectionInfo, atIndex sectionIndex: UInt, forChangeType type: NSFetchedResultsChangeType) {
            
            switch type {
            case .Insert:
                let sectionIndexSet = NSIndexSet(index: Int(sectionIndex))
                self.tableView.insertSections(sectionIndexSet, withRowAnimation: UITableViewRowAnimation.Fade)
            case .Delete:
                let sectionIndexSet = NSIndexSet(index: Int(sectionIndex))
                self.tableView.deleteSections(sectionIndexSet, withRowAnimation: UITableViewRowAnimation.Fade)
            default:
                ""
            }
    }

**Comment by bigfish24** [comment]
Closing this for now, please reopen if you are still facing the issue.
