### ISSUE TITLE
Realm 0.97 throws if notification block is added on thread without runloop

### ISSUE THREAD

**Issue by bigfish24** [Roobiq/RBQFetchedResultsController#52]
`RBQRealmNotificationManager`, should be refactored to use a singleton worker thread that will receive the Realm notifications and pass along changes to `RBQFetchedResultsController` so that the dev never has to worry about passing changes to `RBQRealmNotificationManager` on a background queue/thread that doesn't have a runloop.

**Comment by stephenkopylov** [comment]
Just faced this problem. Really w8 for fix. =)

**Comment by bigfish24** [comment]
Yeah sorry about this probably will be a day or two before I can implement my solution.
