### ISSUE TITLE
Unable to compile RBQFetchResultController with

### ISSUE THREAD

**Issue by jasper-ch-chan** [Roobiq/RBQFetchedResultsController#64]
Has anyone encountered the error "Multiple methods named 'hash' found with mismatched set, parameter type or attributes" in the RBQSafeRealmObject.m file? I've had to comment out the function  

```
(NSUInteger)hash
{
    return [_primaryKeyValue hash];
}
```
to get the code to compile

**Comment by bigfish24** [comment]
Commenting this out will break things. Any chance you could provide me with your project privately to debug? I haven't encountered this error, so it is probably related to the installation or some conflict with Cocoapods assuming you installed that way.

**Comment by bigfish24** [comment]
Also, if you have commented this out, then this is likely the reason why you are not seeing any changes reported in this issue: https://github.com/Roobiq/RBQFetchedResultsController/issues/63

**Comment by jasper-ch-chan** [comment]
@bigfish24 I think the problem is because there are other functions (namely my thrift API) that uses the method name hash, and since _primaryKeyValue is of type id, it can mean any of them. Would it be alright to change it to RLMObject type instead of id?

**Comment by bigfish24** [comment]
@jasper-ch-chan no it does need to be `id` because the primary key value can be `NSString` or `NSNumber` since Realm supports indexes on strings and integers.

**Comment by bigfish24** [comment]
Are you sure you are not conflicting with `hash` which is a method on `NSObject` in your code for the thrift API?

**Comment by jasper-ch-chan** [comment]
So when I command click on the hash function, it shows all the hash functions it finds. NSObject is one of them, but it also lists out all the other hash functions in our API file. Is there another way to get around this?
