### ISSUE TITLE
Swift Example is almost working - except when clicking "Delete" which causesNSInvalidArgumentException

### ISSUE THREAD

**Issue by Brisdo** [Roobiq/RBQFetchedResultsController#7]
The exception happens when clicking the "Delete" button (in the upper left-hand corner) which causes an "'NSInvalidArgumentException', reason: '-[RLMResults isInvalidated]: unrecognized selector sent to instance 0x7fb8b31d1860'".

It looks like objectsWhere (TestObject.objectsWhere("%K == %@","sectionName","First Section")) is handled differently in the Realm-provided RLMSupport.swift and as a result, the results are invalidated...

I updated the swift example pull request.

**Comment by mgleason** [comment]
@Brisdo - really?

The actual error occurs in RBQFetchedResultsController/RLM+Notifications.m in - (void)deleteObjectsWithNotification:(id)array

**Comment by bigfish24** [comment]
the issue is in your code: `TestObject.objectsWhere` returns an `RLMResults` object, which is all you need to pass into `deleteObjectsWithNotification:`. Instead, you are wrapping this in an array, which is why there is a crash.

Here's the correct code:

```
let objectsInFirstSection = TestObject.objectsWhere("%K == %@","sectionName","First Section") as RLMResults
        
realm.beginWriteTransaction()
realm.deleteObjectsWithNotification(objectsInFirstSection)
realm.commitWriteTransaction()
```
