### ISSUE TITLE
Assertion failure "Cache can't be nil"

### ISSUE THREAD

**Issue by jasper-ch-chan** [Roobiq/RBQFetchedResultsController#74]
Occassionally, this assertion fails. I would be able to pull out my data from the cache, then the next second, this assertion fails. I just verified (since I crashed while using the simulator) that the cache folder is not empty. I am unable to reliably reproduce this. Could you provide some insight as to what could be causing this assertion to fail?

**Comment by jasper-ch-chan** [comment]
Its happening more and more now. I haven't done anything different since I started using Realm and this problem wasn't very prevalent until recently.

**Comment by bigfish24** [comment]
@jasper-ch-chan I am not sure unless I can reproduce, can you share your code? We can do this outside of Github.

**Comment by jasper-ch-chan** [comment]
@bigfish24 There are two ways we can do this... We could perhaps skype and I can screen share with you, or we would have to ask you to sign an NDA before I can give you the source code. Which way do you prefer?

**Comment by jasper-ch-chan** [comment]
@bigfish24 I was wondering if you've had some time to think about which way you would prefer to do this to help resolve this problem?

**Comment by bigfish24** [comment]
@jasper-ch-chan sorry for slow reply. Let's go with the NDA route. Realm has an NDA that we use to provide support in this capacity so that we can debug the code, but we have no claims to anything. Ping me at af@realm.io
