### ISSUE TITLE
Uncaught exception 'RLMException', reason: 'Path '(null)' is not valid

### ISSUE THREAD

**Issue by olivierto** [Roobiq/RBQFetchedResultsController#77]
Hello, i'm facing an issue with the RBQFetchedResultsController it crashes systematically... 
the crash log : [crashlog.txt](https://github.com/Roobiq/RBQFetchedResultsController/files/182801/crashlog.txt)

Turns out to be a "RBQSafeObject" that has no "realm" attached and no "realmConfiguration". 
I'm using realm 0.95.3. 

Here is the  code i used to instantiate the controller : 
```objective-c
    @try {
        id <AppServices> service  = self.viewModel.services;
        NSPredicate *predicate = [NSPredicate predicateWithFormat:@"userId == %@",service.userService.userID];
        
        RBQFetchRequest *fetchRequest = [RBQFetchRequest fetchRequestWithEntityName:@"Photo"
                                                                            inRealm:[RLMRealm defaultRealm]
                                                                          predicate:predicate];
        
        
        
        RLMSortDescriptor *sortDescriptor = [RLMSortDescriptor sortDescriptorWithProperty:@"creationTime"
                                                                                ascending:NO];
        
        
        
        fetchRequest.sortDescriptors = @[sortDescriptor];
        
        self.fetchedResultsController = [[RBQFetchedResultsController alloc] initWithFetchRequest:fetchRequest
                                                                               sectionNameKeyPath:nil
                                                                                        cacheName:@"YoobiMyPhotoFetchRC"];
        
        self.fetchedResultsController.delegate = self;
        
        [self.fetchedResultsController performFetch];
    }
    @catch (NSException *exception) {
        LOG_ERROR(0,@"Error with RBQFetch exception : %@",exception);
    }
```

I'm trying to fix it in a fork but not finding the right way... 
ANy help would be much appreciated :) 

Bye!

**Comment by crsantos** [comment]
> Turns out to be a "SafeObject" that has no "realm" attached and no "realmConfiguration".

Usually when I got that symptom, I forgot to add the object to notificationManager:

        [[RBQRealmChangeLogger defaultLogger] didAddObject:object];
        // or 
        [[RBQRealmChangeLogger defaultLogger] didChangeObject:object];

Make sure you do that before calling `[RLMRealm commitWriteTransaction]`

**Comment by olivierto** [comment]
> Usually when I got that symptom, I forgot to add the object to notificationManager:

Nope... unfortunatly all my methods that changes or add objects are already using the logger...

**Comment by crsantos** [comment]
Sorry! My fault, wrong error.
I meant to say: did you add the object to the `RLMRealm`?

    [realm addOrUpdateObject:object];

**Comment by olivierto** [comment]
here is my code : 
```objective-c 
[db beginWriteTransaction];
[db addObjects:returnedObjects];
[[RBQRealmChangeLogger defaultLogger] didAddObjects:returnedObjects];
[db commitWriteTransaction];
```

**Comment by olivierto** [comment]
OMG !!  i tryed with [db addOrUpdateObjects:returnedObjects]; 
And it worked !! I don't understand why because it's only an insert operation :o 
thanks a lot dude!

**Comment by crsantos** [comment]
No problem mate :) That haunted me for at least 2h.

> I don't understand why because it's only an insert operation

If it's and add operations, you can force the `addObjects`
But `addOrUpdateObjects` checks that for you.
