### ISSUE TITLE
Duplicate interface definition for class 'RLMObjectSchema'

### ISSUE THREAD

**Issue by azfx** [Roobiq/RBQFetchedResultsController#8]
I am trying to use this library in my swift project, and am not able to build due to duplicate interface definition error. Any ideas ?

```
#Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!
pod 'RBQFetchedResultsController'
```

![screen shot 2015-04-19 at 6 04 46 pm](https://cloud.githubusercontent.com/assets/4931015/7222241/b8177f3e-e6be-11e4-8e32-fa76707e7e34.png)

**Comment by bigfish24** [comment]
Fixed in https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v1.8.1 just run pod update. Sorry about this!
