### ISSUE TITLE
Use the new notifications API

### ISSUE THREAD

**Issue by kylebshr** [Roobiq/RBQFetchedResultsController#82]
Now that [Realm supports changes](https://realm.io/news/realm-objc-swift-0.99.0/) in notifications, it might be a good idea to see if this works better than the current implementation!

**Comment by hsavit1** [comment]
one thing that the new notifications API doesn't seem to support is section computations... hence why this project still holds value for me :)

**Comment by bigfish24** [comment]
Yep, want to update it for this. Will get to it today. Means no more RBQRealmNotificationManager!

**Comment by bigfish24** [comment]
Fixed: https://github.com/Roobiq/RBQFetchedResultsController/pull/83
