### ISSUE TITLE
getting odd crash when updating objects from a webservice

### ISSUE THREAD

**Issue by skydivedan** [Roobiq/RBQFetchedResultsController#84]
Using RBQFetchedResultsController 4.0
Using RealmSwift 0.99.1

OK, I'm running a query, and getting a Results of "Item" objects. The initial results has no objects in it. This is a first-time run, on an empty database.

Next, I make a call to an external webservice, and I create "Item" objects, from a JSON array that I get back. The results update, and I see the results. So far so good.

I make _another_ call to my webservice. Essentially getting back the exact same list of objects. Those get created in the same way, like this:
`````
try realm.write({ () -> Void in
    // add/update the new items.
    realm.add(items, update: true)
})                        
`````

Except this time, deep in the notification-update block, an exception is thrown.

`        @throw RLMException(@"Object type '%@' not persisted in Realm", className);`

This gets here from `createChangeSetsWithAddedSafeObjects`, which loops through the list of `changedObjects` calling this:

`````
     RLMObject *object = [RBQSafeRealmObject objectfromSafeObject:safeObject];
`````

The className (referenced in the exception) is nil by the way -- unless there's some bad reporting with my debugger. I don't really know what else to do here. This was all working quite well before updating to 0.99.1 of RealmSwift. 

Thanks for any advice you can provide.

**Comment by bigfish24** [comment]
Interesting, let me see if I can reproduce with the demo project, but might need you to share some code (out of band if necessary).

**Comment by thonydam** [comment]
I also updated to 4.0 and seeing the same crash.

**Comment by bigfish24** [comment]
Only with 0.99.1?

**Comment by thonydam** [comment]
I have seen the crash using realm 0.99.0 and 0.99.1

**Comment by bigfish24** [comment]
I find the issue, submitting fix

**Comment by thonydam** [comment]
Awesome! thank you

**Comment by skydivedan** [comment]
ugh, off-by-one errors. Thanks for the fast response, most appreciated.

**Comment by bigfish24** [comment]
Will try to fix today sorry this wasn't smooth roll out
