### ISSUE TITLE
Problem with Realm 0.91.2 or later

### ISSUE THREAD

**Issue by ambas** [Roobiq/RBQFetchedResultsController#9]
After I update realm to 0.91.2, it will crash with `Safe object can't be nil!` message.
But if I force realm to 0.91.1, it work fine :confounded:.

**Comment by bigfish24** [comment]
Fixed in https://github.com/Roobiq/RBQFetchedResultsController/releases/tag/v1.8.2. Seems there is a problem in that Realm release, but I worked around it.

**Comment by ambas** [comment]
Thank you very much :grin:
