### ISSUE TITLE
-[RLMRealm path]: unrecognized selector sent to instance with RBQFRC 4.0.3

### ISSUE THREAD

**Issue by werne2j** [Roobiq/RBQFetchedResultsController#92]
After upgrading Realm to 0.103.1 and RBQFR to 4.0.3 i am getting 
`-[RLMRealm path]: unrecognized selector sent to instance`
When trying to perform a fetch.

I am getting an exception breakpoint at line 1813: RBQFetchedResultsController.m
`NSAssert(safeObject, @"Safe object can't be nil!");`

Was working with Realm 0.98 and RBQFRC 3.0

**Comment by stephenkopylov** [comment]
As I understood - version of RBQFRC you use already supports Fine-grained notifications from Realm.
So, you need to use recommended version of Realm and problem will go away.
Anyway, I can recommend you to move to RBQFRC 4.0.4 and Realm 1.0 - It works nice! =)
