### ISSUE TITLE
Swift-cocoapods Swift Example: RBQSafeRealmObject.h file not found

### ISSUE THREAD

**Issue by finneycanhelp** [Roobiq/RBQFetchedResultsController#94]
RBQSafeRealmObject.h file not found compilation issue.
- git clone http://github.com/Roobiq/RBQFetchedResultsController
- cd RBQFetchedResultsController
- cd Examples
- cd Swift-cocoapods
- pod install
- open RBQFRCSwiftExample.xcworkspace
- compiled

Got compilation error : RBQSafeRealmObject.h file not found

Using cocoapods 1.0.0

**Comment by ngs** [comment]
You need to init submodules.

```sh
git clone http://github.com/Roobiq/RBQFetchedResultsController
cd RBQFetchedResultsController
git submodule update --init --recursive 
```

**Comment by wieseljonas** [comment]
I get the same error when I use the latest version from github.

```
pod 'SwiftFetchedResultsController', :git => 'https://github.com/Roobiq/RBQFetchedResultsController.git'
```
